/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * cloud-crew-api
 * RAPA KAKAO ENG 4 Final Project-Cloud Crew
 * OpenAPI spec version: 1.0.0
 */
import type { GetProject200MetaData } from './getProject200MetaData';

export type GetProject200 = {
  end_point?: string;
  meta_data?: GetProject200MetaData;
};
