/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * cloud-crew-api
 * RAPA KAKAO ENG 4 Final Project-Cloud Crew
 * OpenAPI spec version: 1.0.0
 */
import type { Projects } from './projects';

export type GetProjects200 = {
  projects?: Projects[];
};
