/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * cloud-crew-api
 * RAPA KAKAO ENG 4 Final Project-Cloud Crew
 * OpenAPI spec version: 1.0.0
 */

export type NewProjectBody = {
  /**
   * 프로젝트 이름은 고유해야 하며, 글자 수는 4자 이상 20자 이하로 설정합니다.
   * @minLength 4
   * @maxLength 20
   */
  project_name?: string;
  /** 템플릿은 압축 파일입니다. 파일을 선택하고 이를 버킷에 저장합니다. */
  template?: Blob;
  /** 템플릿에 쓰일 값에 대한 얌 명세서입니다. 파일을 선택하고 이를 버킷에 저장합니다. */
  values?: Blob;
};
