/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * cloud-crew-api
 * RAPA KAKAO ENG 4 Final Project-Cloud Crew
 * OpenAPI spec version: 1.0.0
 */

/**
 * 프로젝트에 관련된 추가 메타데이터. 키-값 쌍으로 구성되며, 값의 타입은 제한하지 않습니다.
 */
export type ProjectsMetaData = { [key: string]: any };
